# **PROBLEM 2: Naive Bayes for Text Classification**

To implement the Naive Bayes classifier with Laplace smoothing, we will follow the given steps:

1. Load the trainSet, trainLabels, trainMap, testSet and testlabels data.

2. Create Document Term Matrix for test data

3. Create Document Tern matrix for train data

In document term matrix, docid is represented by row, term id is represented by columns, count are the entries in the matrix. 
Algorithm: Take the max count for rows and colums to fix the shape of the matrix, then fill the data from Xtrain

4. Then create a Multinomial Naive Bayes model with laplace smoothing i.e. function parameter alpha=1

5. Fit the model in training data and calculate accuracy

6. Predict test data using the generated model


In [14]:
import numpy as np
Xtrain = np.loadtxt("/content/train.data", dtype=int)
print("Xtrain=")
print(Xtrain)

trainMap = np.loadtxt("/content/train.map", dtype=str)
print("trainMap=")
print(trainMap)

Ytrain = np.loadtxt("/content/train.label", dtype=int)
print("Ytrain=")
print(Ytrain)

Xtest = np.loadtxt("/content/test.data", dtype=int)
print("Xtest=")
print(Xtest)

Ytest = np.loadtxt("/content/test.label", dtype=int)
print("Ytest=")
print(Xtest)


Xtrain=
[[    1     1     4]
 [    1     2     2]
 [    1     3    10]
 ...
 [11269 48919     1]
 [11269 51544     1]
 [11269 53958     1]]
trainMap=
[['alt.atheism' '1']
 ['comp.graphics' '2']
 ['comp.os.ms-windows.misc' '3']
 ['comp.sys.ibm.pc.hardware' '4']
 ['comp.sys.mac.hardware' '5']
 ['comp.windows.x' '6']
 ['misc.forsale' '7']
 ['rec.autos' '8']
 ['rec.motorcycles' '9']
 ['rec.sport.baseball' '10']
 ['rec.sport.hockey' '11']
 ['sci.crypt' '12']
 ['sci.electronics' '13']
 ['sci.med' '14']
 ['sci.space' '15']
 ['soc.religion.christian' '16']
 ['talk.politics.guns' '17']
 ['talk.politics.mideast' '18']
 ['talk.politics.misc' '19']
 ['talk.religion.misc' '20']]
Ytrain=
[ 1  1  1 ... 20 20 20]
Xtest=
[[    1     3     1]
 [    1    10     1]
 [    1    12     8]
 ...
 [ 7505 50324     1]
 [ 7505 59935     1]
 [ 7505 61188     2]]
Ytest=
[[    1     3     1]
 [    1    10     1]
 [    1    12     8]
 ...
 [ 7505 50324     1]
 [ 7505 59935     1]
 [ 7505 61188     2]]


In [15]:
# Find maximum value for each column in testX
col_max_vals_test = np.max(Xtest, axis=0)
docs_count_max_test = col_max_vals_test[0]
words_count_max_test = col_max_vals_test[1]

# Initialize empty document-term matrix for test data
document_term_matrix_test = np.zeros((docs_count_max_test, words_count_max_test))

# Fill in the document-term matrix for test data using values from testX
for docid,wordid,cnt in Xtest:
    doc_index = docid - 1  # Subtract 1 to convert to 0-based indexing
    word_index = wordid - 1  # Subtract 1 to convert to 0-based indexing
    count = cnt
    document_term_matrix_test[doc_index][word_index] = count




In [16]:

col_max_vals_train = np.max(Xtrain, axis = 0)
docs_count_max_train = col_max_vals_train[0]
words_count_max_train = col_max_vals_train[1]
shape = (max(docs_count_max_train, docs_count_max_test), max(words_count_max_train, words_count_max_test))
document_term_matrix_train = np.zeros(shape)


# Fill in the document-term matrix for test data using values from testX
for docid,wordid,cnt in Xtrain:
    doc_index = docid - 1  # Subtract 1 to convert to 0-based indexing
    word_index = wordid - 1  # Subtract 1 to convert to 0-based indexing
    count = cnt
    document_term_matrix_train[doc_index][word_index] = count


In [20]:
import numpy as np
from sklearn.naive_bayes import MultinomialNB

# Instantiate the Multinomial Naive Bayes model with alpha=1.0 i.e. Laplace smoothing
nb = MultinomialNB(alpha=1.0)

# Train the model using the training data and labels
nb.fit(document_term_matrix_train, Ytrain)

# Evaluate the model on the test data and labels
accuracy = nb.score(document_term_matrix_test, Ytest)
print("Accuracy: {:.6f}".format(accuracy))

# Make predictions on the test data
predictions = nb.predict(document_term_matrix_test)
print("Predictions:", predictions)

Accuracy: 0.781079
Predictions: [ 1  1  1 ...  1 16  2]


In [21]:
with open("Question2_op.txt", "w") as f:
  f.writelines('\n'.join(str(val) for val in predictions))
f.close()